name: 'Publish preview site on push to main'

on:
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: read
  pages: write
  id-token: write

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build_site:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        
      - name: Setup mkdocs
        run: pip3 install mkdocs
        
      - name: Build site directory with mkdocs
        id: buildsite
        run: mkdocs build
        
      - name: Show site dir
        run: ls ./site/
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload site dir
          path: './site'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
